#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "post-push"
npm run build  
cd build
git init
git remote add origin git@github.com:woodlai/qwerty-learner.git
git branch -m deploy
git add . 
git commit -m 'update deploy' 
git push origin deploy 
